include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_declare_return_types: false
    avoid_types_on_closure_parameters: false
    avoid_unnecessary_containers: false
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: false
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: true
    omit_local_variable_types: false
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_collection_literals: false
    slash_for_doc_comments: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_statements: true
    unnecessary_this: true
    use_key_in_widget_constructors: false